# config.yaml
general:
  land_area_file: landarea.csv
  world_cities_file: worldcities.csv                            # If we want to set the dataset to be HDF5, if not, will export as .pngs 
  country_probabilities_file: country_probabilities.csv         # File location of the probabilities of each country based on land area
  dataset_size: 15000                                           # Size of the dataset (default: 15000) 
  hdf5: true                                                    # If we want to set the dataset to be HDF5, if not, will export as .pngs 
  hdf5_filename: gws10.h5
  debug_mode: false
image:
  width: 512                                                    # Maximum width (640 px)
  height: 512                                                   # Maximum height (640 px)
  views: 4                                                      # Number of views (1 front, 2 front/right, 3 front/right/back, 4 front/right/back/left)
  random_heading: true                                          # Random heading (true) or 0 degree heading (false)